include("Glucose_addition_Mig1.jl")
include("Glucose_addition_Sch9.jl")
include("Glucose_addition.jl")
include("Glucose_starvation.jl")
include("Glutamine_addition_gtr1.jl")
include("Glutamine_addition.jl")
include("Rapamycin_treatment.jl")
include("Rapamycin_wt_sit4.jl")