using Pkg
Pkg.add("CSV")
Pkg.add("DifferentialEquations")
Pkg.add("Plots")
Pkg.add("LinearAlgebra")
Pkg.add("ModelingToolkit")
Pkg.add("SteadyStateDiffEq")
Pkg.add("DiffEqSensitivity")
Pkg.add("LatinHypercubeSampling")
Pkg.add("StatsPlots")
Pkg.add("ForwardDiff")
Pkg.add("DataFrames")